services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./cookies.txt:/app/cookies.txt
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/data.db
      - STORAGE_BASE_PATH=/app/storage
