services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./cookies.txt:/app/cookies.txt
      # 移除 env_file: - .env，因为它不再需要了
      # 你可以在这里继续添加其他需要的配置，例如：
      - SITE_BASE_URL=https://yourdomain.com
