"""add_telegram_bot_token

Revision ID: 2c6338faef8c
Revises: 
Create Date: 2026-04-22 15:13:33.153849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c6338faef8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_bot_token', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
        batch_op.add_column(sa.Column('anki_model_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False, server_default='Basic'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('anki_model_name')
        batch_op.drop_column('telegram_bot_token')

    # ### end Alembic commands ###
