"""add anki_connect_url to user

Revision ID: 81d962b1773d
Revises: 2c6338faef8c
Create Date: 2026-04-23 10:08:35.937115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81d962b1773d'
down_revision: Union[str, Sequence[str], None] = '2c6338faef8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anki_connect_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False, server_default='http://127.0.0.1:8765'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('anki_connect_url')

    # ### end Alembic commands ###
